language: node_js
node_js:
- '4'
deploy:
  api_key:
    secure: PGGvd57ADbMuWldPl3MJg75fV6r0ZV7NEXzcriyPMInGBsWxu62R8wzIQVYeX3f28WwUhwipNCbxs/cEZOegudz1mcW2gRDxATBaNZ/5C4QGdEONI7n3omKkygpFX+iLkzy2Z5mEFuk+qSDj1WzX49I3dVumLjhpdD5uzA7Qp70=
  email: mail@jojow.de
  provider: npm
